humhub/wiki

- messages/fr/base.php
> miss space

- migrations/m201125_034854_alter_content_type_in_wiki_page_review.php
Added migration to alter **content** column to **medium_text** type.
> Wiki character limit on page after a certain amount of words - text does not appear to save and the page seems to max out #145

- docs/CHANGELOG.md
- module.json
- widgets/views/wallEntry.php
Issue: https://github.com/humhub/wiki/issues/171
> Fix wiki stream entry markup

- activities/WikiPageEditedActivity.php
- activities/views/wikiPageEdited.php
- docs/CHANGELOG.md
- models/WikiPage.php
Issue: https://github.com/humhub/wiki/issues/9#issuecomment-865905782
> Add activities for edited Wiki pages

- controllers/PageController.php
- controllers/rest/WikiController.php
- docs/CHANGELOG.md
- models/forms/PageEditForm.php
- tests/codeception/api/PageCest.php
- views/page/edit.php
Issue: https://github.com/humhub/wiki/issues/113
> Handle parallel editing

- controllers/PageController.php
- docs/CHANGELOG.md
- models/forms/PageEditForm.php
- tests/codeception/api/PageCest.php
- views/page/edit.php
Issue: https://github.com/humhub/wiki/issues/113#issuecomment-887351218
> Improve parallel editing

- Events.php
- docs/CHANGELOG.md
Issue: https://github.com/humhub/humhub/issues/4558
> Deprecate CompatModuleManager

- docs/CHANGELOG.md
- views/page/view.php
Issue: https://github.com/humhub/wiki/issues/201
> Fix link color for "Comment" & "Like" from custom theme

- docs/CHANGELOG.md
- models/forms/PageEditForm.php
Issue: https://github.com/humhub/wiki/issues/205
> Fix category selector

- docs/CHANGELOG.md
- widgets/views/categoryListItem.php
Issue: https://github.com/humhub/wiki/issues/224
> Fix sorting in sub-categories

- tests/codeception/_support/AcceptanceTester.php
- tests/codeception/acceptance.suite.yml
Issue: https://github.com/humhub/wiki/issues/235
> Fix acceptance tests

- docs/CHANGELOG.md
- models/WikiPage.php
- module.json
Issue: https://github.com/humhub/wiki/issues/269
> Fix permission to edit wiki page from stream

- docs/CHANGELOG.md
- models/WikiPage.php
- module.json
Issue: https://github.com/humhub/wiki/issues/270
> Rename soft deleted wiki page automatically on creating new page with same name

- views/overview/no-pages.php
Do I need to add such change (one single character) to the changelog?
> Remove wrong character from no-pages.php

- docs/CHANGELOG.md
- widgets/WallEntry.php
- widgets/views/wallEntry.php
Issue: https://github.com/humhub/wiki/issues/279
> Improve text of wiki wall stream entry

- docs/CHANGELOG.md
- views/page/diff.php
https://github.com/humhub/wiki/issues/294
> Fix reverting of old page version

- controllers/ContainerConfigController.php
- controllers/PageController.php
- docs/CHANGELOG.md
https://github.com/humhub/humhub-internal/issues/113
> Fix visibility of the method `Controller::getAccessRules()`

- docs/CHANGELOG.md
- module.json
- tests/codeception/_support/AcceptanceTester.php
- widgets/views/wikiListTable.php
Issue: https://github.com/humhub/humhub-internal/issues/126
> Fix undefined updater

- tests/codeception/_support/AcceptanceTester.php
https://github.com/humhub/team_tasks/issues/284#issuecomment-1908955055
> Fix tests for updated wording

- controllers/ContainerConfigController.php
https://github.com/humhub/humhub-internal/issues/184
> Improve container module settings

- docs/CHANGELOG.md
- module.json
- widgets/WikiMenu.php
https://github.com/humhub/humhub-internal/issues/192
> Add menu item "Move content" on wiki view page

- docs/CHANGELOG.md
- models/WikiPage.php
@luke- in this PR, PhpStorm automatically moved a lot of things to reorganize the code, but the only change is https://github.com/humhub/wiki/compare/fix-allow-saving-pages-from-console?expand=1#diff-eb310bc7e6cec80322e802229ea42d8716ffcec329cdec7e5320d24abc51f525R196
> Allow saving Wiki pages from the console

- docs/CHANGELOG.md
- models/WikiPageRevision.php
- module.json
https://github.com/humhub/humhub-internal/issues/191#issuecomment-2034846937
> [1.16] Update to new search indexing

- controllers/OverviewController.php
- docs/CHANGELOG.md
- module.json
- views/overview/search.php
- widgets/WikiSearchTable.php
- widgets/views/wikiListTable.php
- widgets/views/wikiListTableRow.php
- widgets/views/wikiSearchTable.php
https://github.com/humhub/wiki/issues/322
> Use content searching

- components/WikiPageUrlRule.php
- docs/CHANGELOG.md
Issue https://github.com/humhub/wiki/issues/341
> Fix #341: Controller not found if the Wiki title contains a slash and URL title param cleanup

- docs/CHANGELOG.md
- models/WikiPage.php
- module.json
https://github.com/humhub/wiki/issues/345
> Move child pages to the top level after deleting a parent page

- controllers/OverviewController.php
- docs/CHANGELOG.md
- module.json
https://github.com/humhub/wiki/issues/344
> Fix searching from other content containers

- Events.php
- config.php
- docs/CHANGELOG.md
- module.json
https://github.com/humhub/humhub-internal/issues/167
> Collect user data for Legal module

- controllers/rest/WikiController.php
- docs/CHANGELOG.md
- helpers/HeadlineExtractor.php
- migrations/m141004_022835_initial.php
- models/WikiPage.php
- models/WikiPageRevision.php
- models/forms/ItemDrop.php
- models/forms/PageEditForm.php
- tests/codeception/_support/FunctionalTester.php
- widgets/CategoryListItem.php
- widgets/WikiMenu.php
- widgets/WikiRichTextLinkExtension.php
https://github.com/humhub/wiki/issues/352
> Fix "Move content" menu item visibility for anonymous user

- docs/CHANGELOG.md
- views/page/edit.php
- widgets/WikiMenu.php
https://github.com/humhub/wiki/issues/365
> Update edit page layout

- activities/WikiPageEditedActivity.php
- docs/CHANGELOG.md
- module.json
https://github.com/humhub/wiki/issues/374
> Make activity "Wiki page edited" configurable

- .github/workflows/php-test-master.yml
- .github/workflows/php-test-min-version.yml
- .github/workflows/php-test-next.yml
- docs/CHANGELOG.md
https://github.com/humhub/humhub-internal/issues/844
> Improved Module Test GitHub Actions
